POC: use NTS.Domain.Core objects for JudgeRpcHub Client Procedures
eSolutions-EMS/endurance-management-system pull request #345
Opened 2024-12-20 19:51 UTC by StoyanGoranov

Closes: https://github.com/Not-Endurance/not-timing-system/issues/336

2025-01-14 06:47 UTC, achobanov requested changes

2025-01-14 06:47 UTC, achobanov commented on src/NTS.Application/RPC/IWitnessClientProcedures.cs
> +public interface IWitnessClientProcedures
The idea of this interface was to eventually house non-legacy methods. We don't need it atm, so just rename it to ILegacyWitnessClientProcedures

2025-01-14 06:47 UTC, achobanov commented on src/NTS.Application/RPC/IWitnessHubProcedures.cs
> +public interface IWitnessHubProcedures
Same thing - since we cannot encapsulate the difference between legacy and non-legacy Witness (the signatures change) there is no beneft in naming this interface as non-legacy. Just rename to `ILegacyWitnessHubProcedures`

2025-01-14 06:47 UTC, achobanov commented on src/Judge/NTS.Judge.MAUI.Server/RPC/Procedures/IClientProcedures.cs
> +public interface IClientProcedures
THis interface seems unnecessary

2025-02-08 07:54 UTC, achobanov requested changes

2025-02-08 07:54 UTC, achobanov commented on src/Judge/NTS.Judge/Core/Behinds/RemoteConnectionsCount.cs
> +public class RemoteConnectionsCount : IConnectionsCounter
Naming can be improved

2025-02-08 07:54 UTC, achobanov commented on src/Judge/NTS.Judge/Core/Behinds/RemoteConnectionsCount.cs
> +    }
Why expose public List and public methods to modify the list?

2025-02-08 07:54 UTC, achobanov commented on src/Judge/NTS.Judge/Core/Behinds/RemoteConnectionsCount.cs
> +    }
What's the problem of exposing excessive properties?

2025-02-08 07:54 UTC, achobanov commented on src/Judge/NTS.Judge/Core/Behinds/RemoteConnectionsCount.cs
> +    }
Hint: _encapsulation_. How can we improve encapsulation?

2025-02-08 07:54 UTC, achobanov commented on src/Judge/NTS.Judge/RPC/JudgeRpcClient.cs
> +    public Task DecrementConnectionCount(string connectionId)
Doesn't follow the `Receive`, `Send`, `Get` convention. Also what connection?

2025-02-11 16:08 UTC, StoyanGoranov commented on src/Judge/NTS.Judge/Core/Behinds/RemoteConnectionsCount.cs
> +    }
Encapsulation can be improved by making the stateful property private.

2025-02-14 23:11 UTC, achobanov requested changes

2025-02-14 23:11 UTC, achobanov commented on src/Judge/NTS.Judge.Blazor/Shared/Components/ConnectionStatus/ConnectionStatus.razor.cs
> +        RpcSocket.ServerConnectionChanged += HandleServerConnectionChanged;
If the component subscribes to events, it should also take care to unsubscribe when being disposed. 

Additionally, is this the best place for this logic. Does this UI component need to know about SignalR, RPCs and connections?

2025-02-14 23:11 UTC, achobanov commented on src/Judge/NTS.Judge.MAUI/App.xaml.cs
> +        ContextHelper.ConfigureApplicationName("nts");
random change?

2025-02-14 23:11 UTC, achobanov commented on src/Judge/NTS.Judge.MAUI/MauiProgram.cs
> +                FileName = Path.Combine(currentDirectory, "NTS.SignalR.Server.exe"),
Magic string should be a constant instead. We have constant files for most projects.

2025-02-14 23:11 UTC, achobanov commented on src/Judge/NTS.Judge/Core/Behinds/Adapters/RemoteConnectionsBehind.cs
> +    List<string> ActiveConnections { get; } = [];
Are there any other type of collections?

Private members should be fields by default and properties if only necessary.

2025-02-14 23:11 UTC, achobanov commented on src/Judge/NTS.Judge/Core/Behinds/Adapters/RemoteConnectionsBehind.cs
> +    public void AddConnection(string connectionId)
Connection seems redundant in the name

2025-02-14 23:11 UTC, achobanov commented on src/Judge/NTS.Judge/Core/Behinds/Adapters/RemoteConnectionsBehind.cs
> +    public int GetConnectionsCount()
You could expose a Readonly list instead of providing custom definitions for built in functionalities such as Count.

2025-02-14 23:11 UTC, achobanov commented on src/Judge/NTS.Judge/RPC/JudgeRpcClient.cs
> +public class JudgeRpcClient : RpcClient, IJudgeRpcClient, IStartupInitializer
Clients can be separate, as long as they reuse the same IRpcSocket instance - it's still one connection. You can do `ParticipationClient` and `SateliteConnectionsClient` for example.

2025-02-14 23:11 UTC, achobanov commented on src/NTS.ACL/Handshake/JudgeHandshakeService.cs
> +using static NTS.SignalR.Server.ACL.Constants;
Namespaces should reflect the relative path from the solution root directory.

2025-02-14 23:11 UTC, achobanov commented on src/NTS.Application/ApplicationConstants.cs
> +﻿using NTS.SignalR.Server.ACL;
Namespace

2025-02-14 23:11 UTC, achobanov commented on src/Not/Not.Application/RPC/IConnectionsCounter.cs
> +public interface IConnectionsCounter : IObservableBehind
Is counter a good name for it based on the functionality it exposes?

2025-02-14 23:11 UTC, achobanov commented on src/Not/Not/Contexts/ContextHelper.cs
> +        return _applicationName;
?

2025-02-14 23:11 UTC, achobanov commented on src/Not/Not/Filesystem/FileContextHelper.cs
> +    public static string GetAppDirectory(string subdirectory = "")
Why is this necessary?

2025-02-14 23:11 UTC, achobanov commented on src/Not/Not/ProcessUtility/ProcessServiceContext.cs
> +    public int ParentProcessID { get; set; }
Are consumers supposed to be able to set this value? 

Additionally we don't CAPS abbreviations in dotnet members. I.e. `ParentProcessId`

2025-02-14 23:11 UTC, achobanov commented on src/Not/Not/ProcessUtility/ProcessService.cs
> +public class ProcessService : BackgroundService
One reason this being a HostedService isn't an ideal solution is that this may be problematic or at least pointless if the SignalR.Server starts on its own.

2025-02-14 23:11 UTC, achobanov commented on src/Relay/NTS.SignalR.Server/Middleware/ExceptionHandlingHubFilter.cs
> +            HandleHubException(ex, "OnConnectedAsync");
Use nameof instead of string literals.

2025-02-14 23:11 UTC, achobanov commented on src/Relay/NTS.SignalR.Server/Middleware/ExceptionHandlingHubFilter.cs
> +            return null;
Why null?

2025-02-14 23:11 UTC, achobanov commented on src/Relay/NTS.SignalR.Server/Middleware/ExceptionHandlingHubFilter.cs
> +            return Task.FromException(ex);
Why not use await above?

2025-02-14 23:11 UTC, achobanov commented on src/Relay/NTS.SignalR.Server/Middleware/ExceptionHandlingHubFilter.cs
> +namespace NTS.SignalR.Server.Middleware;
Also namespace doesn't match location. Since we're naming it Relay, then the project can simply be NTS.Relay, as it is a single layer applicaiton

2025-02-14 23:11 UTC, achobanov commented on src/Relay/NTS.SignalR.Server/NTS.SignalR.Server.csproj
> +	  <ProjectReference Include="..\..\NTS.ACL\NTS.ACL.csproj" />
indentation is messy

2025-02-14 23:11 UTC, achobanov commented on src/Relay/NTS.SignalR.Server/Program.cs
> +        logFileConfig.Name = ContextHelper.ConfigureApplicationName("NTS.Judge.Server");
Name can be dynamic here - you can get the current type's namespace for example.

2025-02-16 16:55 UTC, StoyanGoranov commented on src/Not/Not/Contexts/ContextHelper.cs
> +        return _applicationName;
`ContextHelper` was up for deletion as its logic was duplicated in `FileContextHelper` and only used at `App.xaml.cs`. Alternatively, we can delete it `ContextHelper` and replace it with `FileContextHelper`.

2025-02-16 16:56 UTC, StoyanGoranov commented on src/Judge/NTS.Judge.MAUI/App.xaml.cs
> +        ContextHelper.ConfigureApplicationName("nts");
`ContextHelper` was up for deletion as its logic was duplicated in `FileContextHelper` and only used at `App.xaml.cs`. Alternatively, we can delete it `ContextHelper` and replace it with `FileContextHelper`.

2025-02-16 17:36 UTC, StoyanGoranov commented on src/Not/Not.Application/RPC/IConnectionsCounter.cs
> +public interface IConnectionsCounter : IObservableBehind
Naming it Behind is probably better since it is used as one.

2025-02-16 20:07 UTC, StoyanGoranov commented on src/Judge/NTS.Judge/Core/Behinds/Adapters/RemoteConnectionsBehind.cs
> +    List<string> ActiveConnections { get; } = [];
Unsure whether you mean to use another type of collection or that there aren't InactiveConnections. Therefore addressed both by using the `HashSet` type and renaming the field to `_connections`

2025-02-16 21:03 UTC, StoyanGoranov commented on src/Not/Not/Filesystem/FileContextHelper.cs
> +    public static string GetAppDirectory(string subdirectory = "")
So that we don't need a separate overload for method calls when subdirectory is not going to be created.

2025-02-16 21:10 UTC, StoyanGoranov commented on src/Not/Not/ProcessUtility/ProcessService.cs
> +public class ProcessService : BackgroundService
This is addressed in the following conditional statement:
```
if (args.Length > 0)
{
    builder.Services.AddSingleton<ProcessServiceContext>(provider =>
    {
        var parentProcessID = args[0];
        return new ProcessServiceContext(parentProcessID);
    });
    builder.Services.AddHostedService<ProcessService>();
}
```
at Program.cs of the server where the HostedService is registered only if the server is started with the expected argument array.

2025-02-17 16:49 UTC, StoyanGoranov commented on src/Relay/NTS.SignalR.Server/Middleware/ExceptionHandlingHubFilter.cs
> +            return Task.FromException(ex);
Because the `InvokeMethodAsync` of the filter must return an object which represents the next method to be invoked. Not sure if there is a point in making the handler return a task just so it can be awaited. What do you think?

2025-02-17 16:50 UTC, StoyanGoranov commented on src/Relay/NTS.SignalR.Server/Middleware/ExceptionHandlingHubFilter.cs
> +            return Task.FromException(ex);
Also not sure if returning `Task.FromException` is good either.

2025-02-17 17:03 UTC, StoyanGoranov commented on src/Relay/NTS.SignalR.Server/NTS.SignalR.Server.csproj
> +	  <ProjectReference Include="..\..\NTS.ACL\NTS.ACL.csproj" />
this seems like some git mixstake

2025-02-17 22:25 UTC, StoyanGoranov commented on src/Judge/NTS.Judge.Blazor/Shared/Components/ConnectionStatus/ConnectionStatus.razor.cs
> +        RpcSocket.ServerConnectionChanged += HandleServerConnectionChanged;
https://github.com/Not-Endurance/not-timing-system/pull/345/commits/e32e03f0c4bc2a00a31519cb7fceb5cd28eb82b8

2025-02-17 22:27 UTC, StoyanGoranov commented on src/Judge/NTS.Judge/RPC/JudgeRpcClient.cs
> +public class JudgeRpcClient : RpcClient, IJudgeRpcClient, IStartupInitializer
https://github.com/Not-Endurance/not-timing-system/pull/345/commits/46465036366aeced98b1c8b1e9585ead05a29ee9

2025-02-19 17:24 UTC, achobanov commented on src/Judge/NTS.Judge.Blazor/Shared/Components/ConnectionStatus/ConnectionStatus.razor.cs
> +        RpcSocket.ServerConnectionChanged += HandleServerConnectionChanged;
Segregate IConnectionsBehind interface

2025-02-19 17:36 UTC, achobanov commented on src/Judge/NTS.Judge.MAUI/App.xaml.cs
> +        ContextHelper.ConfigureApplicationName("nts");
Use `typeof(x),Namespace!` instead of secondary overload and delte ContextHelper entirely

2025-02-19 17:53 UTC, achobanov commented on src/Not/Not/Filesystem/FileContextHelper.cs
> +    public static string GetAppDirectory(string subdirectory = "")
But we want subdirectories in order to be consistent

2025-02-19 17:58 UTC, achobanov commented on src/Not/Not/ProcessUtility/ProcessService.cs
> +public class ProcessService : BackgroundService
Check agains concrete argument in args

2025-02-19 18:06 UTC, achobanov commented on src/Relay/NTS.SignalR.Server/Middleware/ExceptionHandlingHubFilter.cs
> +            return Task.FromException(ex);
Simply use async when not returning

2025-02-19 18:09 UTC, achobanov requested changes
few comments left

2025-02-28 17:27 UTC, achobanov approved these changes

2025-02-28 17:33 UTC, merged